export { default as Header } from './Header';
export { default as Navbar } from './Navbar';
export { default as Seo } from './Seo';
export { default as About } from './About';
export { default as Skills } from './Skills'
export { default as Project } from './Project';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as SocialMedia } from './SocialMedia';